---
title: "Untitled"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(cmna)
```
```{r}
f <- function(x){
  sqrt(x)-cos(x)
}
curve(f, xlim = c(0,2))
abline(h=0)
abline(v=0)
```

```{r}
f1 <- function(x){
  3*(x+1)*(x-1/2)*(x-1)
}
curve(f, xlim = c(0,3))
abline(h=0)
abline(v=0)
```
```{r}
f2 <- function(x){
  x^3-2*x^2+14*x-6
}
curve(f, xlim = c(0,5))
abline(h=0)
abline(v=0)
```


no.1.a

```{r}
library(cmna)
bisection(f,0,1,tol = 1,m = 10)
```
no.1.b
```{r}
library(cmna)
bisection(f1,-2,1.5,tol = 4,m = 10)
bisection(f1,-1.25,2.5,tol = 4,m = 10)
```
no.1.c
```{r}
library(cmna)
bisection(f2, 0,1,tol = 0.4,m = 10)
bisection(f2,1,3.2,tol = 0.6,m = 10)
bisection(f2,3.2,4,tol = 1,m = 10)
```
no2.a

```{r}
f4 <- function(x){
   x^2 - 6
}
```

```{r}
library(Deriv)
fp <-Deriv(f4)
fp
```

```{r}
library(Deriv)
newton(f4,fp,1, tol = 0.1, m = 10)
```
no.2.b
```{r}
f3 <- function(x){
  x^3 - 2*x^2 +14*x-6
}
```

```{r}
library(Deriv)
fm <-Deriv(f3)
fm
```

```{r}
library(Deriv)
newton(f3,fm,1.5, tol =0.1, m = 10)
```
